In [2]:
from Lib.myModules.my_ML_Modules_1 import *
import math

In [4]:
data_dir = "../data"
infantNum = 4
ECG_dataset = f"{data_dir}/infant{infantNum}_ecg"
RESP_dataset = f"{data_dir}/infant{infantNum}_resp"
# Read all the data
signal_ecg_0 = wfdb.rdsamp(f"{data_dir}/infant{infantNum}_ecg")
signal_resp_0 = wfdb.rdsamp(f"{data_dir}/infant{infantNum}_resp")
print(f'ECG DATA: {signal_ecg_0[1]}')
print(F'RESP DATA: {signal_resp_0[1]}')
totalDuration_ECG = num2Time(num=signal_ecg_0[1]['sig_len'], fs=signal_ecg_0[1]['fs'])
print(f'{totalDuration_ECG} sec, {secs2minutes(totalDuration_ECG)} minutes, {secs2hours(totalDuration_ECG)} hours')
totalDuration_RESP = num2Time(num=signal_resp_0[1]['sig_len'], fs=signal_resp_0[1]['fs'])
print(f'{totalDuration_RESP} sec, {secs2minutes(totalDuration_RESP)} minutes, {secs2hours(totalDuration_RESP)} hours')
# Start and end time defined
# start_time_secs = hours2secs(1)
# end_time_secs = hours2secs(1.1)

def training_pipeline(start_time_secs, end_time_secs):
    ECG_startNum = time2Num(start_time_secs, signal_ecg_0[1]['fs'])
    ECG_endNum = time2Num(end_time_secs, signal_ecg_0[1]['fs'])
    print(f'start: {ECG_startNum}, end: {ECG_endNum}')
    RESP_startNum = time2Num(start_time_secs, signal_resp_0[1]['fs'])
    RESP_endNum = time2Num(end_time_secs, signal_resp_0[1]['fs'])
    print(f'start: {RESP_startNum}, end: {RESP_endNum}')
    signal_ECG, signal_ECG_startTime_secs, signal_ECG_endTime_secs = read_Data(ECG_dataset, startNum=ECG_startNum, endNum=ECG_endNum)
    signal_RESP, signal_RESP_startTime_secs, signal_RESP_endTime_secs = read_Data(RESP_dataset, startNum=RESP_startNum, endNum=RESP_endNum)
    # print(signal_ECG[0].shape)
    signal_ECG_1 = iqr_smooth(signal=signal_ECG[0],hiPerc=90,loPerc=10, cutoff_factor=1)
    # print(signal_RESP[0].shape)
    signal_RESP_1 = iqr_smooth(signal=signal_RESP[0],hiPerc=90,loPerc=10, cutoff_factor=1)
    signal_ECG_2 = norm_signal(signal=signal_ECG_1)
    signal_RESP_2 = norm_signal(signal=signal_RESP_1)
    hrs_0 = cal_heartrate(signal=signal_ECG_2, fs=signal_ECG[1]['fs'])
    rrs_0 = cal_resprate(signal=signal_RESP_2, fs=signal_RESP[1]['fs'])
    if (rrs_0.shape[0] < hrs_0.shape[0]):
        hrs_1 = data_resample(data_fixNan(hrs_0), rrs_0.shape[0])
        rrs_1 = data_fixNan(rrs_0)
    else:
        rrs_1 = data_resample(data_fixNan(rrs_0), hrs_0.shape[0])
        hrs_1 = data_fixNan(hrs_0)
    correlationTest(rrs_1[:],hrs_1[:], plot=False)
    print("---------------------------------------------")
    print("--- Linear Regression ---")
    lr_model_1 = train_lr_model(X=rrs_1, y=hrs_1)
    print("---------------------------------------------")
    print("--- Polynomial Regression ---")
    pr_model_1 = train_pr_model(X=rrs_1, y=hrs_1, degree=6)
    print("---------------------------------------------")
    print("--- SVR Radius Basis Function---")
    svr_rbf_1 = train_svr_rbf_model(X=rrs_1, y=hrs_1, param_C=100, param_gamma=0.1, seed=42)
    print("--- SVR Linear ---")
    svr_lin_1 = train_svr_lin_model(X=rrs_1, y=hrs_1, param_C=1000, param_gamma='auto', seed=42)
    print("--- SVR Polynomial ---")
    svr_poly_1 = train_svr_poly_model(X=rrs_1, y=hrs_1, param_C=1000, param_gamma='auto', param_degree=6, seed=42)

for i in np.arange(1, math.floor(secs2hours(totalDuration_ECG)), 0.1):
    print(f"Data bin: {i}")
    start_time_secs = hours2secs(i)
    end_time_secs = hours2secs(i+0.1)
    training_pipeline(start_time_secs=start_time_secs, end_time_secs=end_time_secs)

ECG DATA: {'fs': 500, 'sig_len': 78684614, 'n_sig': 1, 'base_date': None, 'base_time': None, 'units': ['mV'], 'sig_name': ['II'], 'comments': []}
RESP DATA: {'fs': 50, 'sig_len': 7868296, 'n_sig': 1, 'base_date': None, 'base_time': None, 'units': ['NU'], 'sig_name': ['RESP'], 'comments': []}
157369.228 sec, 2622.8204666666666 minutes, 43.71367444444444 hours
157365.92 sec, 2622.7653333333337 minutes, 43.71275555555556 hours
start: 1800000, end: 1980000
start: 180000, end: 198000
90th percentile: 0.16400837520909167, 10th percentile: -0.23755355254763474, IQR: 0.4015619277567264
Identified outliers: 9621
Data Shape: (180000,)
90th percentile: 24.07121214669968, 10th percentile: 20.537240474173423, IQR: 3.533971672526256
Identified outliers: 83
Data Shape: (18000,)
[[141.78716262  19.45454482]
 [ 19.45454482 249.79800093]]
Pearsons correlation: 0.103
Spearmans correlation: 0.074
---------------------------------------------
--- Linear Regression ---
Coefficient of determination: 0.010454

e:\UniMalaya\MCS-AC\WOA7015AdvancedMachineLearning\FinalExamAssessment\mcs_aml_venv_1\lib\site-packages\scipy\stats\_stats_py.py:4427: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
e:\UniMalaya\MCS-AC\WOA7015AdvancedMachineLearning\FinalExamAssessment\mcs_aml_venv_1\lib\site-packages\scipy\stats\_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))


Identified outliers: 7610
Data Shape: (180000,)
90th percentile: 24.155670091075677, 10th percentile: 0.0, IQR: 24.155670091075677
Identified outliers: 0
Data Shape: (18000,)
[[  304.97961171 -1237.70826106]
 [-1237.70826106  7421.47547464]]
Pearsons correlation: -0.823
Spearmans correlation: -0.768
---------------------------------------------
--- Linear Regression ---
Coefficient of determination: 0.6743277490295156
Intercept: [273.3574]
Coefficients: [[-4.0568786]]
Mean absolute error: 38.39
Mean squared error: 2337.65
Root mean squared error: 48.35
---------------------------------------------
--- Polynomial Regression ---
Coefficient of determination: 0.9597308578125321
Intercept: [180.17581]
Coefficients: [[-9.3233830e-09 -5.6684667e-07 -9.1295924e-06 -1.4946287e-04
   6.5866684e-06 -7.2059890e-08]]
Mean absolute error: 7.49
Mean squared error: 321.45
Root mean squared error: 17.93
---------------------------------------------
--- SVR Radius Basis Function---
Coefficient of deter

e:\UniMalaya\MCS-AC\WOA7015AdvancedMachineLearning\FinalExamAssessment\mcs_aml_venv_1\lib\site-packages\scipy\stats\_stats_py.py:4427: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
e:\UniMalaya\MCS-AC\WOA7015AdvancedMachineLearning\FinalExamAssessment\mcs_aml_venv_1\lib\site-packages\scipy\stats\_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))


Identified outliers: 0
Data Shape: (180000,)
90th percentile: 22.090987450875666, 10th percentile: 22.0812154573115, IQR: 0.009771993564164916
Identified outliers: 0
Data Shape: (18000,)
[[140.47739683   0.        ]
 [  0.           0.        ]]
Pearsons correlation: nan
Spearmans correlation: nan
---------------------------------------------
--- Linear Regression ---
Coefficient of determination: 1.0
Intercept: [0.]
Coefficients: [[-0.]]
Mean absolute error: 0.00
Mean squared error: 0.00
Root mean squared error: 0.00
---------------------------------------------
--- Polynomial Regression ---
Coefficient of determination: 1.0
Intercept: [0.]
Coefficients: [[0. 0. 0. 0. 0. 0.]]
Mean absolute error: 0.00
Mean squared error: 0.00
Root mean squared error: 0.00
---------------------------------------------
--- SVR Radius Basis Function---
Coefficient of determination: 1.0
Intercept: [0.]
Mean absolute error: 0.00
Mean squared error: 0.00
Root mean squared error: 0.00
--- SVR Linear ---
Coef

e:\UniMalaya\MCS-AC\WOA7015AdvancedMachineLearning\FinalExamAssessment\mcs_aml_venv_1\lib\site-packages\scipy\stats\_stats_py.py:4427: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
e:\UniMalaya\MCS-AC\WOA7015AdvancedMachineLearning\FinalExamAssessment\mcs_aml_venv_1\lib\site-packages\scipy\stats\_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))


Identified outliers: 5833
Data Shape: (180000,)
90th percentile: 24.067024149457893, 10th percentile: 21.44324387747958, IQR: 2.623780271978312
Identified outliers: 1719
Data Shape: (18000,)
[[ 230.93574628 -237.95447098]
 [-237.95447098 3239.17970462]]
Pearsons correlation: -0.275
Spearmans correlation: -0.278
---------------------------------------------
--- Linear Regression ---
Coefficient of determination: 0.07737497156449835
Intercept: [120.05312]
Coefficients: [[-1.0451447]]
Mean absolute error: 48.05
Mean squared error: 2991.32
Root mean squared error: 54.69
---------------------------------------------
--- Polynomial Regression ---
Coefficient of determination: 0.15922103989840808
Intercept: [108.84709]
Coefficients: [[-1.1538776e-08 -2.0102983e-07 -9.8688461e-06 -1.5505051e-04
   6.0421330e-06 -5.9516864e-08]]
Mean absolute error: 45.04
Mean squared error: 2875.97
Root mean squared error: 53.63
---------------------------------------------
--- SVR Radius Basis Function---
Coe